### PR TITLE
Fix nullification when there are units

### PR DESCRIPTION
**Pull request by ihough**
Nullification doesn't work when units are specified because value_from_row(row) returns 0.0 if the value is blank. And unit_from_source returns nil if units are blank but then this gets converted to "" by .to_s

### CODE REVIEW

**Comment by rossmeissl** [comment]
So glad I have no idea what Ian is talking about

**Comment by ihough** [comment]
Aren't you proud of my first pull request ;)

**Comment by rossmeissl** [comment]
I'll be proud if it gets merged :sparkles: :heart: :sparkles:

**Comment by ihough** [comment]
Yo Seamus reaction? I need nullification to work...

**Pull request merged**
